### ISSUE TITLE
Penambahan fungsional summary 3.0

### ISSUE THREAD

**Issue by vicky45** [AnandaAlfa001/bpk_office#17]
permintaan customer, fungsional summary, yang menampilkan segala hasil dari rekapan acara, terkait hasil polling peserta, like unlike, dan peserta-peserta yang tersambung dalam sistem tersebut

**Comment by AnandaAlfa001** [comment]
Oke bisa diterima, dengan tujuan untuk mempermudah perekapan dari admin sendiri tentang hasil dari event tersebut

**Comment by AnandaAlfa001** [comment]
silahkan diupload CR nya
